GE-1804
CareCloud/Data-Science-Extensions pull request #3
Opened 2021-08-05 13:42 UTC by MTBC-EDI-AK154

Please review the code and let me know of the changes.

2021-08-05 21:34 UTC, apulido-carecloud commented on .github/workflows/Build_and_Test.yml
> +name: Build and Test
This project is built using maven not sbt. Please check the readme file on the project.
https://github.com/CareCloud/Data-Science-Extensions/tree/master/spark-datasource-rest

This is the command to build/install it locally:
`mvn clean install -pl spark-datasource-rest -DskipTests -Dscalastyle.skip=true`

You will have to use a similar approach to the ones used in the legacy edi projects
https://github.com/CareCloud/edi_core/blob/master/.github/workflows/publish.yml

@AsfaMumtaz24 has been doing most of the development in this project. Please reach out to her if you have any questions.

2021-08-05 21:34 UTC, apulido-carecloud requested changes
see comments

2021-08-09 09:57 UTC, MTBC-EDI-AK154 commented
Please Now Try and run on the main Repo to see it deploy as it is not giving me the permission to publish.

2021-08-18 21:08 UTC, apulido-carecloud approved these changes

2021-08-18 21:08 UTC, merged